apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: image-pull-secrets
  namespace: resource-locker-operator
spec:
  patches:
  - id: aiopsanalyticsorchestrator-locker
    patchTemplate: |
      spec:
        pullSecrets:
        - ibm-entitlement-key
    patchType: application/merge-patch+json
    targetObjectRef:
      apiVersion: ai.ir.aiops.ibm.com/v1beta1
      kind: AIOpsAnalyticsOrchestrator
      name: aiops
      namespace: {{.Values.aiManager.namespace}}
  - id: aiops-topology-service-account-locker
    patchTemplate: |
      imagePullSecrets:
      - name: ibm-entitlement-key
      metadata:
        labels:
          managedByUser: "true"
    patchType: application/strategic-merge-patch+json
    targetObjectRef:
      apiVersion: v1
      kind: ServiceAccount
      name: aiops-topology-service-account
      namespace: {{.Values.aiManager.namespace}}
  serviceAccountRef:
    name: resource-locker-operator-controller-manager
