{{- if .Values.spec.aiManager.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress-and-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: {{.Values.spec.aiManager.namespace}}
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
{{- end }}